#!/usr/bin/env bash

adb root
adb wait-for-device
adb shell pm disable com.android.provision
adb shell settings put global device_provisioned 1
adb shell settings put secure user_setup_complete 1
adb shell pm disable com.xiaomi.account
